"""Known species and breeds for local fuzzy matching.

These lists mirror the frontend selects and are used to normalize
breed/species values extracted by the LLM without spending tokens.
"""

SPECIES = [
    {"title": "Cão", "value": "dog"},
    {"title": "Gato", "value": "cat"},
]

# Flat list for matching
SPECIES_TITLES = [s["title"] for s in SPECIES]

DOG_BREEDS = [
    "American Bully Pocket (TIPO)",
    "Biewer Terrier",
    "Affenpinscher",
    "Airedale Terrier",
    "Akita",
    "Akita Americano",
    "Alano Espanhol",
    "Alaskan Malamute",
    "Alpenländische Dachsbacke",
    "American Bully (TIPO)",
    "American Staffordshire Terrier",
    "Anglo-Français de Petite Vénerie",
    "Antigo Cão de Parar Dinamarquês",
    "Antigo Cão de Pastor Inglês",
    "Ariégeois",
    "Australian Kelpie",
    "Australian Silky Terrier",
    "Australian Stumpy Tail Cattle Dog",
    "Azawahk",
    "Baixote ( Teckel )",
    "Barbado da Terceira",
    "Basenji",
    "Basset Artesién Normand",
    "Basset Bleu de Gascogne",
    "Basset da Vestefália",
    "Basset Fauve de Bretagne",
    "Basset Hound",
    "Basset Sueco",
    "Bayrischer Gebirgsschweisshund",
    "Beagle",
    "Beagle-Harrier",
    "Bearded Collie",
    "Bedlington Terrier",
    "Bichon Bolonhês",
    "Bichon Frisé",
    "Bichon Havanês",
    "Bichon Maltês",
    "Billy",
    "Black and Tan Coonhound",
    "Border Collie",
    "Border Terrier",
    "Boston Terrier",
    "Bouledogue Francês",
    "Boxer",
    "Braco Alemão de pêlo curto",
    "Braco de Ariège",
    "Braco de Auvergne",
    "Braco de Bourbonais",
    "Braco de Weimar",
    "Braco Francês tipo Gascónia",
    "Braco Francês tipo Pirinéus",
    "Braco Húngaro de pêlo cerdoso",
    "Braco Húngaro de pêlo curto",
    "Braco Italiano",
    "Braco Saint-German",
    "Briquet Griffon Vendéen",
    "Broholmer",
    "Bull Terrier Miniatura",
    "Bull Terrier Standard",
    "Bulldog Continental",
    "Bulldog Inglês",
    "Bullmastiff",
    "Cairn Terrier",
    "Canaan Dog",
    "Canadian Eskimo Dog",
    "Cane Corso Italiano",
    "Caniche",
    "Cão Boieiro Australiano",
    "Cão Boieiro da Flandres",
    "Cão Boieiro das Ardenas",
    "Cão Boieiro de Appenzell",
    "Cão Boieiro de Berna",
    "Cão Boieiro de Entlebuch",
    "Cão Caçador de Alces Norueguês Cinzento",
    "Cão Caçador de Alces Norueguês Preto",
    "Cão Caçador de Alces Sueco",
    "Cão da Dalmácia",
    "Cão da Gronelândia",
    "Cão da Serra da Estrela",
    "Cão da Serra de Aires",
    "Cão da Terra Nova",
    "Cão de Água Americano",
    "Cão de Água Espanhol",
    "Cão de Água Francês",
    "Cão de Água Frísio",
    "Cão de Água Irlandês",
    "Cão de Água Português",
    "Cão de Castro Laboreiro",
    "Cão de Fila de São Miguel",
    "Cão de Gado Transmontano",
    "Cão de Montanha dos Pirinéus",
    "Cão de Parar Alemão de pêlo cerdoso",
    "Cão de Parar Alemão de pêlo comprido",
    "Cão de Parar Alemão de pêlo duro (Deutsch Drathaar)",
    "Cão de Pastor Alemão",
    "Cão de Pastor Australiano",
    "Cão de Pastor Belga",
    "Cão de Pastor Bergamasco",
    "Cão de Pastor Branco Suíço",
    "Cão de Pastor Catalão",
    "Cão de Pastor Croata",
    "Cão de Pastor da Ásia Central",
    "Cão de Pastor da Picardia",
    "Cão de Pastor da Rússia Meridional",
    "Cão de Pastor das Shetland",
    "Cão de Pastor de Beauce",
    "Cão de Pastor de Brie",
    "Cão de Pastor de Kraski",
    "Cão de Pastor do Atlas",
    "Cão de Pastor do Cáucaso",
    "Cão de Pastor dos Pirinéus de face rasa",
    "Cão de Pastor dos Pirinéus de pêlo comprido",
    "Cão de Pastor Finlandês da Lapónia",
    "Cão de Pastor Holandês",
    "Cão de Pastor Islandês",
    "Cão de Pastor Jugoslavo",
    "Cão de Pastor Kangal",
    "Cão de Pastor Maiorquino",
    "Cão de Pastor Maremmano-Abruzzese",
    "Cão de Pastor Polaco das Planícies",
    "Cão de Pastor Polaco de Tatra",
    "Cão de Pastor Romeno de Bucovina",
    "Cão de Pastor Romeno dos Cárpatos",
    "Cão de Pastor Romeno Mioritico",
    "Cão de Presa Maiorquino",
    "Cão de Santo Huberto",
    "Cão de São Bernardo",
    "Cão de Ursos da Carélia",
    "Cão do Barrocal Algarvio",
    "Cão dos Faraós",
    "Cão Finlandês da Lapónia",
    "Cão Lobo Checoslovaco",
    "Cão Lobo de Saarloos",
    "Cão Sem Pêlo do México",
    "Cão Sem Pêlo do Perú",
    "Cão Sueco da Lapónia",
    "Carlin ( Pug )",
    "Cavalier King Charles Spaniel",
    "Cesky Fousek",
    "Chesapeake Bay Retriever",
    "Chien d'Artois",
    "Chihuahua",
    "Chinese Crested Dog",
    "Chongqing Dog",
    "Chow Chow",
    "Cimarron Uruguaio",
    "Cirneco dell'Etna",
    "Clumber Spaniel",
    "Cocker Spaniel Americano",
    "Cocker Spaniel Inglês",
    "Collie de pêlo comprido",
    "Collie de pêlo curto",
    "Coton de Tuléar",
    "Curly Coated Retriever",
    "Dandie Dinmont Terrier",
    "Dansk-Svensk Gardshund",
    "Dobermann",
    "Dogue Alemão",
    "Dogue Argentino",
    "Dogue de Bordéus",
    "Dogue do Tibete",
    "English Springer Spaniel",
    "English Toy Terrier",
    "Epagneul Anão Continental",
    "Epagneul Azul da Picardia",
    "Epagneul Bretão",
    "Epagneul de Pont-Audemer",
    "Epagneul Francês",
    "Epagneul Japonês",
    "Epagneul Pequinês",
    "Epagneul Picard",
    "Eurasier",
    "Exotic Bully Micro (TIPO)",
    "Field Spaniel",
    "Fila Brasileiro",
    "Flat Coated Retriever",
    "Fox Terrier de pêlo cerdoso",
    "Fox Terrier de pêlo liso",
    "Foxhound Americano",
    "Foxhound Inglês",
    "Galgo Afegão",
    "Galgo Árabe ( Sloughi )",
    "Galgo Escocês",
    "Galgo Espanhol",
    "Galgo Húngaro",
    "Galgo Inglês",
    "Galgo Irlandês",
    "Galgo Polaco",
    "Galgo Russo",
    "Galguinho Italiano",
    "Gascon Saintongeois",
    "Golden Retriever",
    "Gonczy Polski",
    "Grand Basset Griffon Vendéen",
    "Grand Griffon Vendéen",
    "Grande Boieiro Suíço",
    "Grande Sabujo Anglo-Francês Branco e Laranja",
    "Grande Sabujo Anglo-Francês Branco e Preto",
    "Grande Sabujo Anglo-Francês Tricolor",
    "Grande Sabujo Azul da Gascónia",
    "Griffon Belga",
    "Griffon Bleu de Gascogne",
    "Griffon de Bruxelas",
    "Griffon Fauve de Bretagne",
    "Griffon Nivernais",
    "Hannover'scher Schweisshund",
    "Harrier",
    "Hokkaïdo",
    "Hollandse Smoushond",
    "Hovawart",
    "Indefinida",
    "Irish Glen of Imaal Terrier",
    "Irish Soft Coated Wheaten Terrier",
    "Jack Russell Terrier",
    "Kai",
    "Kerry Blue Terrier",
    "King Charles Spaniel",
    "Kishu",
    "Komondor",
    "Korea Jindo Dog",
    "Korthals",
    "Kromfohrländer",
    "Kuvasz",
    "Labrador Retriever",
    "Lagotto Romagnolo",
    "Laika da Sibéria Ocidental",
    "Laika da Sibéria Oriental",
    "Laika Russo-Europeia",
    "Lakeland Terrier",
    "Lancashire Heeler",
    "Landseer",
    "Leonberger",
    "Lhasa Apso",
    "Manchester Terrier",
    "Maneto",
    "Mastim dos Pirinéus",
    "Mastim Espanhol",
    "Mastim Inglês",
    "Mastim Napolitano",
    "Miniature American Shepherd",
    "Mudi",
    "Münsterländer Grande",
    "Münsterländer Pequeno",
    "Norfolk Terrier",
    "Norrbottenspets",
    "Norsk Buhund",
    "Norsk Lundehund",
    "Norwich Terrier",
    "Nova Scotia Duck Tolling Retriever",
    "Otterhound",
    "Pachon Navarro",
    "Parson Russell Terrier",
    "Pastor Garafiano",
    "Pequeno Cão Holandês de Caça Aquática",
    "Pequeno Cão Leão",
    "Pequeno Cão Russo",
    "Pequeno Sabujo Azul da Gascónia",
    "Pequeno Sabujo Suíço",
    "Perdigueiro de Burgos",
    "Perdigueiro de Drente",
    "Perdigueiro Português",
    "Petit Basset Griffon Vendéen",
    "Petit Brabançon",
    "Pinscher Alemão",
    "Pinscher Austríaco",
    "Pinscher Miniatura",
    "Pit Bull Terrier",
    "Pit Monster (TIPO)",
    "Podengo Andaluz",
    "Podengo Canário",
    "Podengo Ibicenco",
    "Podengo Português",
    "Pointer",
    "Poitevin",
    "Porcelaine",
    "Presa Canário",
    "Pudelpointer",
    "Puli",
    "Pumi",
    "Rafeiro do Alentejo",
    "Rateiro de Praga (Prazsky Krysarik)",
    "Ratonero Valenciano",
    "Ratonero-Bodeguero Andaluz",
    "Rhodesian Ridgeback ( Leão da Rodésia )",
    "Rottweiler",
    "Sabujo Alemão",
    "Sabujo Austríaco preto afogueado",
    "Sabujo da Bósnia de pêlo duro (Barak)",
    "Sabujo da Ístria de pêlo curto",
    "Sabujo da Ístria de pêlo duro",
    "Sabujo da Transilvânia",
    "Sabujo de Halden",
    "Sabujo de Hamilton",
    "Sabujo de Hygen",
    "Sabujo de Posavaz",
    "Sabujo de Schiller",
    "Sabujo de Småland",
    "Sabujo do Tirol",
    "Sabujo Eslovaco",
    "Sabujo Espanhol",
    "Sabujo Finlandês",
    "Sabujo Francês Branco e Laranja",
    "Sabujo Francês Branco e Preto",
    "Sabujo Francês Tricolor",
    "Sabujo Grego",
    "Sabujo Montenegrino de Montanha",
    "Sabujo Norueguês",
    "Sabujo Polaco",
    "Sabujo Sérvio",
    "Sabujo Sérvio Tricolor",
    "Sabujo Suíço",
    "Saluki",
    "Samoiedo",
    "Schapendoes",
    "Schipperke",
    "Schnauzer Gigante",
    "Schnauzer Médio",
    "Schnauzer Miniatura",
    "Sealyham Terrier",
    "Segugio Italiano de pêlo cerdoso",
    "Segugio Italiano de pêlo curto",
    "Segugio Maremmano",
    "Setter Gordon",
    "Setter Inglês",
    "Setter Irlandês Vermelho",
    "Setter Irlandês Vermelho e Branco",
    "Shar Pei",
    "Shiba",
    "Shih Tzu",
    "Shikoku",
    "Siberian Husky",
    "Skye Terrier",
    "Slovenský Cuvac",
    "Slovenský Hrubosrsty Stavac (Ohar)",
    "Spaniel Alemão",
    "Spaniel do Tibete",
    "Spinone Italiano",
    "Spitz Alemão",
    "Spitz dos Visigodos",
    "Spitz Finlandês",
    "Spitz Japonês",
    "Stabyhoun",
    "Staffordshire Bull Terrier",
    "Steirische Rauhhaarbracke",
    "Sussex Spaniel",
    "Taiwan Dog",
    "Terrier Australiano",
    "Terrier Brasileiro",
    "Terrier Checo",
    "Terrier de Caça Alemão",
    "Terrier do Tibete",
    "Terrier Escocês",
    "Terrier Irlandês",
    "Terrier Japonês",
    "Terrier Preto Russo",
    "Thai Bangkaew Dog",
    "Thai Ridgeback Dog",
    "Tornjak",
    "Tosa",
    "Volpino Italiano",
    "Welsh Corgi Cardigan",
    "Welsh Corgi Pembroke",
    "Welsh Springer Spaniel",
    "Welsh Terrier",
    "West Highland White Terrier",
    "Whippet",
    "Yakutskaya Laika",
    "Yorkshire Terrier",
]

CAT_BREEDS = [
    "Abissinio",
    "American Curl de Pelo Curto",
    "American Curl de Pelo Longo",
    "Angorá Turco",
    "Azul Russo",
    "Balinês",
    "Bengal",
    "Britânico de Pelo Curto",
    "Britânico de Pelo Longo",
    "Burmês",
    "Burmilla",
    "Chartreux",
    "Cornish Rex",
    "Cymric",
    "Devon Rex",
    "Doméstico de Pelo Curto",
    "Doméstico de Pelo Longo",
    "Don Sphynx",
    "Europeu",
    "Exótico",
    "Gato Bosques da Noruega",
    "Gato de Raça Indefinida",
    "German Rex",
    "Japanese Bobtail",
    "Korat",
    "Kurilean Bobtail de Pelo Curto",
    "Kurilean Bobtail de Pelo Longo",
    "LaPerm de Pelo Curto",
    "LaPerm de Pelo Longo",
    "Lykoi",
    "Maine Coon",
    "Manx",
    "Mau Egípcio",
    "Neva Masquerade",
    "Ocicat",
    "Oriental de Pelo Curto",
    "Oriental de Pelo Longo",
    "Persa",
    "Peterbald",
    "Ragdoll",
    "Sagrado da Birmânia",
    "Selkirk Rex de Pelo Curto",
    "Selkirk Rex de Pelo Longo",
    "Siamês",
    "Siberiano",
    "Singapura",
    "Snowshoe",
    "Sokoke",
    "Somali",
    "Sphynx",
    "Thai",
    "Van Turco",
]

ALL_BREEDS = DOG_BREEDS + CAT_BREEDS
